# Generated by Django 5.2.7 on 2025-10-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='valid_to',
            new_name='valid_until',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='valid_from',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Foiz'), ('fixed', 'Summaga')], max_length=10),
        ),
    ]
