# Generated by Django 5.2.7 on 2025-10-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_memoryoption_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'Есть в наличии'), ('out_of_stock', 'Нет в наличии'), ('pre_order', 'Предзаказ')], default='in_stock', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(choices=[('free', 'Бесплатная доставка'), ('courier', 'Доставка курьером'), ('pickup', 'Самовывоз')], default='courier', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='lifespan',
            field=models.CharField(choices=[('1', '1 год'), ('3', '3 года'), ('5', '5 лет'), ('10', '10 лет')], default='5', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei'), ('other', 'Другой')], default='apple', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup',
            field=models.CharField(choices=[('available', 'Доступен в Ташкенте'), ('unavailable', 'Недоступен')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('6', '6 месяцев'), ('12', '12 месяцев'), ('24', '24 месяца'), ('36', '36 месяцев')], default='12', max_length=50),
        ),
    ]
