# Generated by Django 5.2.7 on 2025-10-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_availability_product_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='construction',
            field=models.CharField(blank=True, choices=[('foldable', 'Складной'), ('waterproof', 'Влагозащита'), ('standard', 'Обычный')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Masalan: 146.7 x 71.5 x 7.4 mm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Металл'), ('plastic', 'Пластик'), ('glass', 'Стекло'), ('ceramic', 'Керамика')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('other', 'Другая')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sim_count',
            field=models.PositiveIntegerField(choices=[(1, '1 SIM'), (2, '2 SIM'), (3, '3 SIM')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('smartphone', 'Смартфон'), ('tablet', 'Планшет'), ('watch', 'Смарт-часы'), ('laptop', 'Ноутбук')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='grammda', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sim_type',
            field=models.CharField(blank=True, choices=[('nano', 'Nano SIM'), ('micro', 'Micro SIM'), ('e-sim', 'eSIM')], max_length=50, null=True),
        ),
    ]
