# Generated by Django 5.2.7 on 2025-10-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_construction_product_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body_type',
        ),
        migrations.DeleteModel(
            name='SimType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
    ]
