# Generated by Django 5.2.7 on 2025-10-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_body_type_delete_simtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
