# Generated by Django 5.2.7 on 2025-10-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_accessory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Стандарт', 'Стандарт'), ('Мини', 'Мини')], max_length=100),
        ),
    ]
